# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'convertedTemperatureDialogBox.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_convertedTemperatureDialog(object):
    def setupUi(self, convertedTemperatureDialog):
        convertedTemperatureDialog.setObjectName("convertedTemperatureDialog")
        convertedTemperatureDialog.resize(240, 320)
        convertedTemperatureDialog.setToolTipDuration(2)
        self.convertedTemperature = QtWidgets.QLineEdit(convertedTemperatureDialog)
        self.convertedTemperature.setGeometry(QtCore.QRect(60, 50, 113, 91))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.convertedTemperature.setFont(font)
        self.convertedTemperature.setToolTipDuration(2)
        self.convertedTemperature.setAlignment(QtCore.Qt.AlignCenter)
        self.convertedTemperature.setReadOnly(True)
        self.convertedTemperature.setObjectName("convertedTemperature")
        self.convertedTemperatureLabel = QtWidgets.QLabel(convertedTemperatureDialog)
        self.convertedTemperatureLabel.setGeometry(QtCore.QRect(40, 10, 141, 31))
        self.convertedTemperatureLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.convertedTemperatureLabel.setObjectName("convertedTemperatureLabel")
        self.buttonBox = QtWidgets.QDialogButtonBox(convertedTemperatureDialog)
        self.buttonBox.setGeometry(QtCore.QRect(40, 180, 156, 23))
        self.buttonBox.setToolTipDuration(2)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName("buttonBox")

        self.retranslateUi(convertedTemperatureDialog)
        self.buttonBox.clicked['QAbstractButton*'].connect(convertedTemperatureDialog.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(convertedTemperatureDialog)

    def retranslateUi(self, convertedTemperatureDialog):
        _translate = QtCore.QCoreApplication.translate
        convertedTemperatureDialog.setWindowTitle(_translate("convertedTemperatureDialog", "convertedTemperature"))
        convertedTemperatureDialog.setToolTip(_translate("convertedTemperatureDialog", "convertedTemperature"))
        convertedTemperatureDialog.setStatusTip(_translate("convertedTemperatureDialog", "convertedTemperature"))
        convertedTemperatureDialog.setWhatsThis(_translate("convertedTemperatureDialog", "convertedTemperature"))
        convertedTemperatureDialog.setAccessibleName(_translate("convertedTemperatureDialog", "convertedTemperature"))
        convertedTemperatureDialog.setAccessibleDescription(_translate("convertedTemperatureDialog", "convertedTemperature"))
        self.convertedTemperature.setToolTip(_translate("convertedTemperatureDialog", "ConvertedTemperature"))
        self.convertedTemperature.setStatusTip(_translate("convertedTemperatureDialog", "ConvertedTemperature"))
        self.convertedTemperature.setWhatsThis(_translate("convertedTemperatureDialog", "ConvertedTemperature"))
        self.convertedTemperature.setAccessibleName(_translate("convertedTemperatureDialog", "ConvertedTemperature"))
        self.convertedTemperature.setAccessibleDescription(_translate("convertedTemperatureDialog", "ConvertedTemperature"))
        self.convertedTemperature.setText(_translate("convertedTemperatureDialog", "0"))
        self.convertedTemperatureLabel.setText(_translate("convertedTemperatureDialog", "Your Temperature"))
        self.buttonBox.setToolTip(_translate("convertedTemperatureDialog", "OK"))
        self.buttonBox.setStatusTip(_translate("convertedTemperatureDialog", "OK"))
        self.buttonBox.setWhatsThis(_translate("convertedTemperatureDialog", "OK"))
        self.buttonBox.setAccessibleName(_translate("convertedTemperatureDialog", "OK"))
        self.buttonBox.setAccessibleDescription(_translate("convertedTemperatureDialog", "OK"))
