# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'temperatureConverter.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(427, 346)
        MainWindow.setToolTipDuration(2)
        MainWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        MainWindow.setUnifiedTitleAndToolBarOnMac(True)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.celciusButton = QtWidgets.QPushButton(self.centralwidget)
        self.celciusButton.setGeometry(QtCore.QRect(70, 20, 132, 51))
        self.celciusButton.setToolTipDuration(2)
        self.celciusButton.setObjectName("celciusButton")
        self.fahrenheightButton = QtWidgets.QPushButton(self.centralwidget)
        self.fahrenheightButton.setGeometry(QtCore.QRect(220, 20, 131, 51))
        self.fahrenheightButton.setMinimumSize(QtCore.QSize(0, 23))
        self.fahrenheightButton.setToolTipDuration(2)
        self.fahrenheightButton.setObjectName("fahrenheightButton")
        self.conversionLabel = QtWidgets.QLabel(self.centralwidget)
        self.conversionLabel.setGeometry(QtCore.QRect(80, 70, 271, 41))
        self.conversionLabel.setScaledContents(True)
        self.conversionLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.conversionLabel.setObjectName("conversionLabel")
        self.temperatureSetting = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.temperatureSetting.setGeometry(QtCore.QRect(140, 120, 131, 81))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.temperatureSetting.setFont(font)
        self.temperatureSetting.setToolTipDuration(2)
        self.temperatureSetting.setDecimals(1)
        self.temperatureSetting.setMinimum(-999.9)
        self.temperatureSetting.setMaximum(999.9)
        self.temperatureSetting.setSingleStep(0.1)
        self.temperatureSetting.setStepType(QtWidgets.QAbstractSpinBox.DefaultStepType)
        self.temperatureSetting.setObjectName("temperatureSetting")
        self.temperatureLabel = QtWidgets.QLabel(self.centralwidget)
        self.temperatureLabel.setGeometry(QtCore.QRect(10, 140, 121, 31))
        self.temperatureLabel.setObjectName("temperatureLabel")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Temperature Converter"))
        MainWindow.setToolTip(_translate("MainWindow", "Temperature Converter"))
        MainWindow.setStatusTip(_translate("MainWindow", "Temperature Converter"))
        MainWindow.setWhatsThis(_translate("MainWindow", "Temperature Converter"))
        MainWindow.setAccessibleName(_translate("MainWindow", "Temperature Converter"))
        MainWindow.setAccessibleDescription(_translate("MainWindow", "Temperature Converter"))
        self.celciusButton.setToolTip(_translate("MainWindow", "Celcius"))
        self.celciusButton.setStatusTip(_translate("MainWindow", "Celcius"))
        self.celciusButton.setWhatsThis(_translate("MainWindow", "Celcius"))
        self.celciusButton.setAccessibleName(_translate("MainWindow", "Celcius"))
        self.celciusButton.setAccessibleDescription(_translate("MainWindow", "Celcius"))
        self.celciusButton.setText(_translate("MainWindow", "Celcius"))
        self.fahrenheightButton.setToolTip(_translate("MainWindow", "Fahrenheight"))
        self.fahrenheightButton.setStatusTip(_translate("MainWindow", "Fahrenheight"))
        self.fahrenheightButton.setWhatsThis(_translate("MainWindow", "Fahrenheight"))
        self.fahrenheightButton.setAccessibleName(_translate("MainWindow", "Fahrenheight"))
        self.fahrenheightButton.setAccessibleDescription(_translate("MainWindow", "Fahrenheight"))
        self.fahrenheightButton.setText(_translate("MainWindow", "Fahrenheight"))
        self.conversionLabel.setText(_translate("MainWindow", "Please select your conversion method"))
        self.temperatureSetting.setToolTip(_translate("MainWindow", "TemperatureSetting"))
        self.temperatureSetting.setStatusTip(_translate("MainWindow", "TemperatureSetting"))
        self.temperatureSetting.setWhatsThis(_translate("MainWindow", "TemperatureSetting"))
        self.temperatureSetting.setAccessibleName(_translate("MainWindow", "TemperatureSetting"))
        self.temperatureSetting.setAccessibleDescription(_translate("MainWindow", "TemperatureSetting"))
        self.temperatureLabel.setText(_translate("MainWindow", "Enter the Temperature"))
